AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Parameters:
  Name:
    Description: Personal Budget ETL Lambda
    Type: String
    Default: daily-transactions-etl
  Version:
    Type: String
    Description: Version of file that contains lambda code
    Default: 0.0.1

Resources:

  Role:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Ref Name
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/personal-budget-transactions
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/personal-budget-transactions/*
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:usaa/creds-??????
      RoleName: !Ref Name

  PersonalBudgetEtlLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Extracts bank transaction data and saves it to dynamo"
      FunctionName: !Ref Name
      Handler: main.lambda_handler
      MemorySize: 512
      Timeout: 300
      Code:
        S3Bucket: "my-personal-budget"
        S3Key: !Sub "personal-budget-${Version}.zip"
      Role:
        Fn::GetAtt:
          - Role
          - Arn
      Runtime: python3.8
      Environment:
        Variables:
          REGION_NAME: !Sub "${AWS::Region}"
          INSTITUTION_NAME: USAA
          USAA_CREDS_SECRET_NAME: usaa/creds
          TRANSACTIONS_DYNAMO_TABLE_NAME: personal-budget-transactions
          NUM_OF_TRANSACTION_DAYS: 1
          VERSION: !Ref Version