AWSTemplateFormatVersion: '2010-09-09'
Description: ''

Resources:
  TransactionsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: personal-budget-transactions
      KeySchema:
        - AttributeName: internal_id
          KeyType: HASH
        - AttributeName: date  # The sort key.
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: internal_id
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true