---
Resources:

  CodeBuildDependencyCacheBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pip-dependencies
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  CodeBuildArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-personal-budget
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:GetObject
                  - s3:GetBucket
                  - s3:List*
                Effect: Allow
                Resource:
                  - arn:aws:s3:::maven-build-settings
                  - arn:aws:s3:::maven-build-settings/*
              - Action: ssm:GetParameters
                Effect: Allow
                Resource: "*"
              - Action: cloudformation:*
                Effect: Allow
                Resource: "*"
              - Action:
                  - iam:*
                  - logs:*
                  - ssm:*
                  - lambda:*
                Effect: Allow
                Resource: "*"
            Version: '2012-10-17'
          PolicyName: policy_0

  CodeBuildRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - CodeBuildArtifactBucket
                  - Arn
              - Fn::Join:
                  - ''
                  - - Fn::GetAtt:
                        - CodeBuildArtifactBucket
                        - Arn
                    - "/*"
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - CodeBuildDependencyCacheBucket
                  - Arn
              - Fn::Join:
                  - ''
                  - - Fn::GetAtt:
                        - CodeBuildDependencyCacheBucket
                        - Arn
                    - "/*"
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ''
                  - - 'arn:'
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - ":log-group:/aws/codebuild/"
                    - Ref: CodeBuildProject
              - Fn::Join:
                  - ''
                  - - 'arn:'
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - ":log-group:/aws/codebuild/"
                    - Ref: CodeBuildProject
                    - ":*"
        Version: '2012-10-17'
      PolicyName: CodeBuildRoleDefaultPolicy
      Roles:
        - Ref: CodeBuildRole

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Location:
          Ref: CodeBuildArtifactBucket
        NamespaceType: BUILD_ID
        Packaging: ZIP
        Path: build/  # todo:  change this!
        Type: S3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:1.0
        PrivilegedMode: false  # False - because we don't need to use docker for this build pipeline.
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ENV
            Type: PLAINTEXT
            Value: dev
      ServiceRole:
        Fn::GetAtt:
          - CodeBuildRole
          - Arn
      Source:
        GitCloneDepth: 1
        Location: https://github.com/jones-chris/personal-budget.git
        ReportBuildStatus: true
        Type: GITHUB
      BadgeEnabled: true
      Cache:
        Location:
          Fn::Join:
            - "/"
            - - Ref: CodeBuildDependencyCacheBucket
              - Ref: AWS::NoValue
        Type: S3
      Name: personal-budget
      SourceVersion: master